[package]
name = "binja-load-uaf"
description = "Reproduce Binja load uaf"
publish = false

version = "0.1.0"
edition = "2024"

[dependencies]
binaryninja = { git = "https://github.com/Vector35/binaryninja-api.git", rev="6769870863027693679119152863982393639882" }
thiserror = "2.0"
